import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  assertGitBoundFiles,
  buildFrontendHandoff,
  validateFrontendHandoff,
} from "../../scripts/contract-drift-check.mjs";

const outputs = [
  "src/lib/bff-v1/agora/contract-snapshot.json",
  "src/lib/bff-v1/agora/types.ts",
];
const contract = {
  generated_from_contract_commit: "1".repeat(40),
  bundle_index_sha256: "2".repeat(64),
  openapi_sha256: "3".repeat(64),
};

describe("contract generation Git provenance", () => {
  let root: string;
  let originalCommit: string;

  function git(...args: string[]): string {
    return execFileSync("git", ["-C", root, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  }

  function write(rel: string, data: string): void {
    const target = path.join(root, rel);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, data);
  }

  function commit(): string {
    git("add", ".");
    git("-c", "user.name=Provenance test fixture", "-c", "user.email=fixture@example.invalid",
      "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", "Isolated fixture output");
    return git("rev-parse", "HEAD");
  }

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), "contract-provenance-"));
    git("init", "--quiet");
    write(outputs[0], '{"version":"test"}\n');
    write(outputs[1], "export interface ResearchRun { status: string }\n");
    originalCommit = commit();
  });

  afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

  it("binds actual committed output and accepts unchanged bytes in a descendant", () => {
    const handoff = buildFrontendHandoff(root, contract);
    expect(handoff.frontend.runtime_commit).toBe(originalCommit);
    write("evidence.txt", "A later handoff commit does not change generated output.\n");
    commit();
    expect(() => validateFrontendHandoff(root, handoff, contract)).not.toThrow();
  });

  it("refuses to bind uncommitted generated bytes to HEAD", () => {
    write(outputs[1], "export interface ResearchRun { provenance: string }\n");
    expect(() => buildFrontendHandoff(root, contract)).toThrow("Git bytes mismatch");
  });

  it("rejects newly generated bytes attributed to the previous runtime even with a matching digest", () => {
    write(outputs[1], "export interface ResearchRun { provenance: string }\n");
    const updatedCommit = commit();
    const handoff = buildFrontendHandoff(root, contract);
    expect(handoff.frontend.runtime_commit).toBe(updatedCommit);
    expect(() => validateFrontendHandoff(root, handoff, contract)).not.toThrow();
    handoff.frontend.runtime_commit = originalCommit;
    expect(() => validateFrontendHandoff(root, handoff, contract)).toThrow("Git bytes mismatch");
  });

  it("rejects unknown, placeholder and unrelated runtime commits", () => {
    const handoff = buildFrontendHandoff(root, contract);
    for (const invalid of ["0".repeat(40), "HEAD", "f".repeat(40)]) {
      expect(() => validateFrontendHandoff(root, {
        ...handoff, frontend: { ...handoff.frontend, runtime_commit: invalid },
      }, contract)).toThrow();
    }
    git("checkout", "--orphan", "unrelated");
    write("unrelated.txt", "Distinct root with the same generated output.\n");
    const unrelated = commit();
    git("checkout", "--detach", originalCommit);
    handoff.frontend.runtime_commit = unrelated;
    expect(() => validateFrontendHandoff(root, handoff, contract)).toThrow("ancestor of HEAD");
  });

  it("rejects contract, output path, algorithm and digest changes", () => {
    const handoff = buildFrontendHandoff(root, contract);
    expect(() => validateFrontendHandoff(root, handoff, {
      ...contract, generated_from_contract_commit: "4".repeat(40),
    })).toThrow("generated_from_contract_commit mismatch");
    expect(() => validateFrontendHandoff(root, {
      ...handoff, generation_metadata: { ...handoff.generation_metadata, expected_output_paths: [outputs[1]] },
    }, contract)).toThrow("algorithms or output paths");
    expect(() => validateFrontendHandoff(root, {
      ...handoff, generation_metadata: { ...handoff.generation_metadata, generated_types_hash_algorithm: "unchecked" },
    }, contract)).toThrow("algorithms or output paths");
    write(outputs[0], '{"tampered":true}\n');
    expect(() => validateFrontendHandoff(root, handoff, contract)).toThrow("generated_types_sha256 mismatch");
  });

  it("checks inherited schema bytes against the declared backend contract commit", () => {
    const inheritedSchema = "services/control-plane/specs/agora/v4/research_run_projection.schema.json";
    write(inheritedSchema, '{"properties":{"status":{"type":"string"}}}\n');
    const oldContract = commit();
    const newBytes = '{"properties":{"status":{"type":"string"},"provenance":{"type":"string"}}}\n';
    write(inheritedSchema, newBytes);
    const newContract = commit();
    const hashes = { [inheritedSchema]: crypto.createHash("sha256").update(newBytes).digest("hex") };
    expect(() => assertGitBoundFiles(root, oldContract, hashes)).toThrow("Git bytes mismatch");
    expect(() => assertGitBoundFiles(root, newContract, hashes)).not.toThrow();
  });
});
