// Management Agent — Lovable AI powered chat agent.
// TEST MODE: no auth. Re-enable JWT + per-user RLS before production.
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { createOpenAICompatible } from "npm:@ai-sdk/openai-compatible";
import {
  convertToModelMessages,
  stepCountIs,
  streamText,
  tool,
  type UIMessage,
} from "npm:ai";
import { z } from "npm:zod";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY")!;
const BFF_BASE_URL =
  Deno.env.get("PANTHEON_BFF_BASE_URL") ??
  "https://pantheon-lupin-dev-bff.34.81.75.241.sslip.io";

const gateway = createOpenAICompatible({
  name: "lovable",
  baseURL: "https://ai.gateway.lovable.dev/v1",
  headers: {
    "Lovable-API-Key": LOVABLE_API_KEY,
    "X-Lovable-AIG-SDK": "vercel-ai-sdk",
  },
});

const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

type AgentMode = "auto" | "draft" | "confirm" | "agent";

const BASE_SYSTEM_PROMPT = `You are the Pantheon Management Cockpit assistant — a senior operator copilot.

You have FOUR operating modes (chosen by user per message):
- **auto**: read-only execution. Query / navigate freely; no write tools available.
- **draft**: never write to the backend; produce form drafts via propose_* tools (they only stage payloads + navigate).
- **confirm**: write actions allowed but MUST use needsApproval tools (decide_inbox_item, create_ask, create_persona, create_strategy, create_capital_pool, create_rebalance, create_deployment, create_ranking_formula, create_research_experiment, create_skill, retire_persona, decide_intervention, request_sentinel_remediation, trigger_readiness).
- **agent**: multi-step autonomy; chain query_* → propose_* / decide_* / create_* freely. Confirm-tier tools still require approval.

Tool catalogue:
- Read: query_cockpit, query_persona_league (RANKING snapshot, may lag), query_persona_fleet (REGISTRY, real-time — use this to verify a newly created persona), query_portfolio_book, query_trading_pulse, query_human_inbox, query_alerts.
- Navigation: navigate(href).
- Draft (draft/agent): propose_inbox_decision, propose_ask, propose_create_persona. These DO NOT call backend — they only stage a draft and navigate.
- High-risk write (confirm/agent): decide_inbox_item, create_ask, decide_intervention, request_sentinel_remediation, trigger_readiness.
- Entity create (confirm/agent, needsApproval): create_persona, create_strategy, create_capital_pool, create_rebalance, create_deployment, create_ranking_formula, create_research_experiment, create_skill.
- Entity lifecycle (confirm/agent, needsApproval): retire_persona.

Entity creation rules — IMPORTANT:
- "Create / 建立 / 新增 N personas / strategies / capital pools / ..." → in **confirm**/**agent** mode, call the matching create_* tool ONCE PER ENTITY (N times for N entities). Do NOT use create_ask for entity creation. Do NOT navigate one page per entity — navigation is for showing the user a page, not for creating records.
- After creating personas, call query_persona_fleet (NOT persona_league) to verify the new ids appear in the registry. persona_league is a ranking snapshot and may not show fresh entities.
- In **draft** mode, use propose_create_persona instead (stages a prefill and opens /management/personas?intent=create).
- **Interventions cannot be created directly by anyone.** They are auto-generated by Sentinel remediation. If the user wants a new intervention against an existing entity, call \`request_sentinel_remediation(findingId, plan)\`. To act on an existing intervention, use \`decide_intervention(id, decision, memo)\`.
- The legacy \`create_intervention\` tool has been removed (no such endpoint exists in the BFF spec).

Entity deletion rules — IMPORTANT:
- **Personas cannot be deleted.** Per Pack D StateMachine Contract (D02), persona is an audit entity; physical delete would break the evidence chain (audit retained 7 years). If the user asks to "delete / 刪除 / 移除 / 砍掉" a persona, do NOT search for a delete tool — instead use \`retire_persona(id, memo)\` to move it to the \`retired\` terminal state. Briefly explain that retired personas remain in the audit log but are hidden from default listings, and that replacement uses Fork from Retired.

Evidence wall & Evolution Journal rules — IMPORTANT:
- The current BFF exposes **ONLY** a read explorer at \`GET /bff/management/evidence\` and the read page \`/management/evolution-journal\`. There is **NO write endpoint** for evidence annotation, evolution journal entries, or audit notes. The legacy \`annotate_evidence\` tool has been removed (it always 404'd).
- If the user asks to "記錄到 evidence / 標註 / 寫進 journal / 留下對帳 / annotate / pin to evidence / log to journal", do **NOT** pretend to write. Reply: "目前 BFF 沒有 evidence/journal 寫入端點，只有查詢。請改走 Human Inbox（create_ask）或 Ask 通道留下備註，或我帶你到 /management/evidence 用 explorer 過濾。" Then \`navigate('/management/evidence')\` or \`navigate('/management/human-inbox')\`.

CRITICAL — Do NOT pre-narrate tool success:
- Before a tool call returns, NEVER use past tense to describe its effect ("我已經...", "已標註", "已寫入", "已彙整到 X", "I have logged...", "I've recorded..."). Use future tense before calling ("我將呼叫 ..."), then report based on the actual \`ok: true/false\` in the result.
- For audit entities (Evidence wall, Evolution Journal, Audit log), NEVER claim a write happened unless the corresponding tool is listed in the Tool catalogue above with a needsApproval write path. As of now, none exist — so any "已記錄到 evidence/journal" statement is forbidden.

Rules:
- Always cite real data from tool results; never invent numbers or IDs.
- Respond in user's language (default 繁體中文; English when prompted).
- In **draft** mode, NEVER call decide_inbox_item / create_ask / create_* / decide_intervention / request_sentinel_remediation / trigger_readiness — use propose_* instead.
- In **auto** mode, you have NO write tools; if user asks for one, refuse and suggest switching to confirm/agent.
- In **confirm** mode, prefer needsApproval tools when the user wants to commit.
- Before any destructive action, briefly explain why and what will happen.
- Available surfaces: /management/cockpit, /management/persona-fleet, /management/personas, /management/strategies, /management/capital, /management/deployments, /management/tools, /management/mcps, /management/skills, /management/rules, /management/evals, /management/datasets, /management/channels, /management/webhooks, /management/human-inbox, /management/trading-pulse, /management/portfolio-book, /management/persona-league, /management/quarterly-ranking, /management/performance-attribution, /management/evolution-journal, /management/evidence, /management/sentinel, /management/interventions, /management/readiness/{bff-ha,broker-live,capital-binding-live,ep5,strict-publish}.
- Keep responses concise. Use markdown.`;



function modeHint(mode: AgentMode): string {
  switch (mode) {
    case "auto":
      return `\n\nCURRENT MODE = **auto** (read-only). You have ONLY query_* + navigate tools. You MAY NOT call any write tool. If the user asks for a write/annotate/log action, refuse and suggest switching to confirm/agent (or, for evidence/journal, explain there is no BFF write endpoint at all).`;
    case "draft":
      return `\n\nCURRENT MODE = **draft**. You MUST NOT call decide_inbox_item / create_ask / decide_intervention / request_sentinel_remediation / trigger_readiness. Use propose_inbox_decision / propose_ask instead — they stage a draft and navigate the user to the relevant page.`;
    case "confirm":
      return `\n\nCURRENT MODE = **confirm** (default). For any backend write, use the needsApproval tools so the user can review and approve.`;
    case "agent":
      return `\n\nCURRENT MODE = **agent**. You may chain multiple tool calls autonomously. High-risk tools still pause for approval. End with a short summary of what you did.`;
  }
}

// ─── BFF auth header injection ─────────────────────────────────
// Dev BFF uses a stub bearer token of the form "<operatorId>:<roles>[:mfa]".
// Frontend sends `bffAuth: { token?, tenantId? }` in the request body;
// otherwise we fall back to env, then to the hardcoded dev default.
const DEV_BEARER_FALLBACK = "pantheon-dev-browser:reviewer";
const BFF_API_VERSION = "2026-05-07";

interface BffAuth { token?: string | null; tenantId?: string | null }

function resolveAuth(input: BffAuth | undefined): { token: string; tenantId: string | null } {
  const token =
    input?.token?.trim() ||
    Deno.env.get("PANTHEON_BFF_DEV_BEARER_TOKEN")?.trim() ||
    DEV_BEARER_FALLBACK;
  const tenantId =
    input?.tenantId?.trim() ||
    Deno.env.get("PANTHEON_BFF_TENANT_ID")?.trim() ||
    null;
  return { token, tenantId };
}

function newCorrelationId(): string {
  return `cid_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 12)}`;
}
function idempotencyKey(): string {
  return `idk_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 12)}`;
}

function bffHeaders(auth: BffAuth | undefined, mutation: boolean): Record<string, string> {
  const { token, tenantId } = resolveAuth(auth);
  const h: Record<string, string> = {
    "Accept": "application/json",
    "Authorization": `Bearer ${token}`,
    "X-Correlation-Id": newCorrelationId(),
    "X-BFF-Api-Version": BFF_API_VERSION,
  };
  if (tenantId) h["X-Tenant-Id"] = tenantId;
  if (mutation) {
    h["Content-Type"] = "application/json";
    h["Idempotency-Key"] = idempotencyKey();
  }
  return h;
}

interface ToolErrorEnvelope {
  ok: false;
  status: number;
  code?: string;
  i18nKey?: string;
  message: string;
  correlationId?: string;
}

async function bffCall(
  path: string,
  init: RequestInit & { auth?: BffAuth },
): Promise<unknown> {
  const method = init.method ?? "GET";
  const mutation = method !== "GET" && method !== "HEAD";
  const headers = { ...bffHeaders(init.auth, mutation), ...(init.headers as Record<string, string> | undefined) };
  try {
    const r = await fetch(`${BFF_BASE_URL}${path}`, { ...init, headers });
    const text = await r.text();
    let parsed: unknown = text;
    try { parsed = JSON.parse(text); } catch { /* keep text */ }
    if (!r.ok) {
      const err = (parsed && typeof parsed === "object" ? (parsed as { error?: { code?: string; i18nKey?: string; message?: string } }).error : null) ?? null;
      const env: ToolErrorEnvelope = {
        ok: false,
        status: r.status,
        code: err?.code,
        i18nKey: err?.i18nKey,
        message: err?.message ?? `BFF ${method} ${path} failed (${r.status})`,
        correlationId: headers["X-Correlation-Id"],
      };
      return env;
    }
    return { ok: true, status: r.status, data: parsed };
  } catch (e) {
    const env: ToolErrorEnvelope = {
      ok: false,
      status: 0,
      code: "NETWORK_ERROR",
      message: e instanceof Error ? e.message : String(e),
      correlationId: headers["X-Correlation-Id"],
    };
    return env;
  }
}

function bffGet(path: string, auth?: BffAuth): Promise<unknown> {
  return bffCall(path, { method: "GET", auth });
}

function buildTools(mode: AgentMode, auth: BffAuth | undefined) {
  const tools: Record<string, ReturnType<typeof tool>> = {
    navigate: tool({
      description: "Navigate the user's browser to a management surface route. Use absolute paths like /management/human-inbox.",
      inputSchema: z.object({
        href: z.string().describe("App route, e.g. /management/cockpit"),
        reason: z.string().optional(),
      }),
    }),
    query_cockpit: tool({
      description: "Fetch the management cockpit snapshot.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/management/cockpit", auth),
    }),
    query_persona_league: tool({
      description: "Fetch persona league RANKING snapshot. May lag — does NOT reflect newly created personas. To verify a newly created persona is registered, use query_persona_fleet instead.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/management/persona-league", auth),
    }),
    query_persona_fleet: tool({
      description: "Fetch the persona REGISTRY (real-time). Use this to verify a newly created persona appears in the system. Returns the full fleet with lifecycle states.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/management/persona-fleet", auth),
    }),
    query_portfolio_book: tool({
      description: "Fetch portfolio book overview.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/management/portfolio-book", auth),
    }),
    query_trading_pulse: tool({
      description: "Fetch trading pulse comparison.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/management/trading-pulse", auth),
    }),
    query_human_inbox: tool({
      description: "List human inbox items.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/approvals", auth),
    }),
    query_alerts: tool({
      description: "List recent system alerts.",
      inputSchema: z.object({}),
      execute: async () => bffGet("/bff/alerts", auth),
    }),

    annotate_evidence: tool({
      description: "Attach a tag or short note to an evidence item. LOW RISK — executes immediately in auto/agent mode.",
      inputSchema: z.object({
        evidenceId: z.string(),
        tag: z.string().optional(),
        note: z.string().max(280).optional(),
      }),
      execute: async ({ evidenceId, tag, note }) =>
        bffCall(`/bff/evidence/${encodeURIComponent(evidenceId)}/annotate`, {
          method: "POST",
          body: JSON.stringify({ tag, note }),
          auth,
        }),
    }),

    propose_inbox_decision: tool({
      description: "Stage a DRAFT inbox decision (approve/reject/defer) with reason. Does NOT call backend — user will review and submit from the Human Inbox page.",
      inputSchema: z.object({
        itemId: z.string(),
        action: z.enum(["approve", "reject", "defer"]),
        reason: z.string().min(3),
      }),
      execute: async ({ itemId, action, reason }) => ({
        ok: true,
        kind: "draft",
        target: "human-inbox",
        href: "/management/human-inbox",
        payload: { itemId, action, reason },
        note: "Draft staged. Open Human Inbox to review and submit.",
      }),
    }),
    propose_ask: tool({
      description: "Stage a DRAFT Ask (question for a persona). Does NOT call backend — user will review and submit from the Persona Fleet page.",
      inputSchema: z.object({
        target: z.string().describe("persona id or name"),
        question: z.string().min(3),
      }),
      execute: async ({ target, question }) => ({
        ok: true,
        kind: "draft",
        target: "persona-fleet",
        href: "/management/persona-fleet",
        payload: { target, question },
        note: "Draft staged. Open Persona Fleet to review and submit.",
      }),
    }),

    decide_inbox_item: tool({
      description: "Approve, reject, or defer a human-inbox item. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        itemId: z.string(),
        action: z.enum(["approve", "reject", "defer"]),
        reason: z.string().min(3),
      }),
      needsApproval: true,
      execute: async ({ itemId, action, reason }) =>
        bffCall(`/bff/management/human-inbox/${encodeURIComponent(itemId)}`, {
          method: "POST",
          body: JSON.stringify({ action, reason }),
          auth,
        }),
    }),
    create_ask: tool({
      description: "Open an Ask channel. HIGH RISK — requires user approval.",
      inputSchema: z.object({ target: z.string(), question: z.string().min(3) }),
      needsApproval: true,
      execute: async ({ target, question }) =>
        bffCall(`/bff/agora/ask/sessions`, {
          method: "POST",
          body: JSON.stringify({ target, question }),
          auth,
        }),
    }),
    decide_intervention: tool({
      description: "Decide an EXISTING intervention (approve/reject/defer). HIGH RISK — requires user approval. Use this only when an intervention id already exists.",
      inputSchema: z.object({
        id: z.string().describe("intervention id"),
        decision: z.enum(["approve", "reject", "defer"]),
        memo: z.string().min(3),
      }),
      needsApproval: true,
      execute: async ({ id, decision, memo }) =>
        bffCall(`/bff/v5/interventions/${encodeURIComponent(id)}/decide`, {
          method: "POST",
          body: JSON.stringify({ decision, memo }),
          auth,
        }),
    }),
    request_sentinel_remediation: tool({
      description: "Ask Sentinel to build a remediation plan for an EXISTING finding. This is how a new intervention is born (interventions cannot be created directly). HIGH RISK — requires user approval.",
      inputSchema: z.object({
        findingId: z.string(),
        plan: z.object({
          kind: z.enum(["pause", "throttle", "freeze", "rollback", "capital_cut", "custom"]),
          target: z.string().describe("entity id the plan acts on"),
          memo: z.string().optional(),
        }),
      }),
      needsApproval: true,
      execute: async ({ findingId, plan }) =>
        bffCall(`/bff/v5/sentinel/remediation/build`, {
          method: "POST",
          body: JSON.stringify({ findingId, plan }),
          auth,
        }),
    }),
    trigger_readiness: tool({
      description: "Trigger a readiness re-check. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        check: z.enum(["bff-ha", "broker-live", "capital-binding-live", "ep5", "strict-publish"]),
      }),
      needsApproval: true,
      execute: async ({ check }) =>
        bffCall(`/bff/management/readiness/${check}`, {
          method: "POST",
          auth,
        }),
    }),

    // ─── Entity create tools (P0-D, BE verified ready 2026-05-28) ───
    // Each is needsApproval:true. Call ONCE per entity; for N entities, call N times.
    create_persona: tool({
      description: "Create a new persona entity (Registry). HIGH RISK — requires user approval. For multiple personas, call this tool repeatedly (once per persona). After creating, call query_persona_fleet to verify.",
      inputSchema: z.object({
        name: z.string().min(1),
        archetype: z.string().optional().describe("e.g. generalist, momentum, mean-reversion"),
        description: z.string().optional(),
        initialMode: z.enum(["live", "paper", "shadow", "suspended"]).optional(),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/personas`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_strategy: tool({
      description: "Create a new strategy entity. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        alpha: z.string().optional(),
        capitalPoolId: z.string().optional(),
        personaIds: z.array(z.string()).optional(),
        risk: z.enum(["low", "medium", "high"]).optional(),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/strategies`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_capital_pool: tool({
      description: "Create a new capital pool. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        currency: z.string().default("USD"),
        allocated: z.number().nonnegative().default(0),
        riskBudget: z.number().nonnegative().default(0),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/capital-pools`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_rebalance: tool({
      description: "Create a rebalance plan. Requires an existing capital_pool_id. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        quarter: z.string().describe("e.g. 2026Q2"),
        capital_pool_id: z.string().describe("Required. Target capital pool id."),
      }),
      needsApproval: true,
      execute: async ({ name, quarter, capital_pool_id }) =>
        bffCall(`/bff/rebalances`, {
          method: "POST",
          body: JSON.stringify({ name, quarter, capital_pool_id, targetPoolId: capital_pool_id }),
          auth,
        }),
    }),
    create_deployment: tool({
      description: "Create a deployment of a strategy artifact to paper/live. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        strategyId: z.string(),
        artifactId: z.string(),
        target: z.enum(["paper", "live", "shadow"]).default("paper"),
        version: z.string().default("0.0.1"),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/deployments`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_ranking_formula: tool({
      description: "Create a new ranking formula expression. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        expression: z.string().min(1).describe("e.g. sharpe, 0.6*sharpe + 0.4*sortino"),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/ranking-formulas`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_research_experiment: tool({
      description: "Create a new research experiment. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        hypothesis: z.string().min(1),
        metric: z.string().default("sharpe"),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/research-experiments`, { method: "POST", body: JSON.stringify(input), auth }),
    }),
    create_skill: tool({
      description: "Create a new skill entity. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        name: z.string().min(1),
        description: z.string().optional(),
      }),
      needsApproval: true,
      execute: async (input) =>
        bffCall(`/bff/skills`, { method: "POST", body: JSON.stringify(input), auth }),
    }),

    // Persona lifecycle (retire = terminal, not delete). HIGH RISK.
    retire_persona: tool({
      description: "Retire (archive) a persona to the terminal `retired` state. Use this when the user asks to 'delete / remove / 刪除 / 移除 / 砍掉' a persona — physical delete is forbidden by D02 StateMachine Contract because persona is an audit entity. Retired personas remain in the audit log (7-year retention) but are hidden from default listings. HIGH RISK — requires user approval.",
      inputSchema: z.object({
        id: z.string().describe("persona id"),
        memo: z.string().min(8).describe("audit memo (≥8 chars) explaining why retiring"),
      }),
      needsApproval: true,
      execute: async ({ id, memo }) =>
        bffCall(`/bff/actions/persona/${encodeURIComponent(id)}/retire`, {
          method: "POST",
          body: JSON.stringify({ memo }),
          auth,
        }),
    }),

    // Draft variant for draft mode — does NOT call backend, just stages prefill.
    propose_create_persona: tool({
      description: "Stage a DRAFT persona create payload. Does NOT call backend — user will review and submit from /management/personas.",
      inputSchema: z.object({
        name: z.string().min(1),
        archetype: z.string().optional(),
        description: z.string().optional(),
        initialMode: z.enum(["live", "paper", "shadow", "suspended"]).optional(),
      }),
      execute: async (input) => ({
        ok: true,
        kind: "draft",
        target: "personas",
        href: "/management/personas?intent=create",
        payload: input,
        note: "Draft staged. Open the Personas page to review and submit.",
      }),
    }),
  };

  const CREATE_TOOLS = [
    "create_persona", "create_strategy", "create_capital_pool", "create_rebalance",
    "create_deployment", "create_ranking_formula", "create_research_experiment", "create_skill",
  ] as const;
  const LIFECYCLE_TOOLS = ["retire_persona"] as const;

  if (mode === "draft") {
    delete tools.decide_inbox_item;
    delete tools.create_ask;
    delete tools.decide_intervention;
    delete tools.request_sentinel_remediation;
    delete tools.trigger_readiness;
    delete tools.annotate_evidence;
    for (const k of CREATE_TOOLS) delete tools[k];
    for (const k of LIFECYCLE_TOOLS) delete tools[k];
  } else if (mode === "auto") {
    delete tools.decide_inbox_item;
    delete tools.create_ask;
    delete tools.decide_intervention;
    delete tools.request_sentinel_remediation;
    delete tools.trigger_readiness;
    delete tools.propose_inbox_decision;
    delete tools.propose_ask;
    delete tools.propose_create_persona;
    for (const k of CREATE_TOOLS) delete tools[k];
    for (const k of LIFECYCLE_TOOLS) delete tools[k];
  } else if (mode === "confirm") {
    delete tools.propose_inbox_decision;
    delete tools.propose_ask;
    delete tools.propose_create_persona;
  } else {
    // agent: keep create_*, retire_*, and propose_create_persona available
  }



  return tools;
}

const responseHeaders = { ...corsHeaders, "X-Pantheon-Test-Mode": "true" };

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: responseHeaders });

  console.warn("[management-agent] TEST MODE: no auth");

  try {
    const body = await req.json() as {
      messages: UIMessage[];
      threadId: string;
      anonId: string;
      mode?: AgentMode;
      bffAuth?: BffAuth;
    };
    const { messages, threadId, anonId, bffAuth } = body;
    const mode: AgentMode = body.mode && ["auto", "draft", "confirm", "agent"].includes(body.mode)
      ? body.mode
      : "confirm";
    if (!Array.isArray(messages) || !threadId || !anonId) {
      return new Response(JSON.stringify({ error: "Invalid request: messages, threadId, anonId required" }), {
        status: 400, headers: { ...responseHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: thread } = await admin
      .from("chat_threads")
      .select("id, user_id, title")
      .eq("id", threadId)
      .maybeSingle();
    if (!thread) {
      await admin.from("chat_threads").insert({ id: threadId, user_id: anonId, title: "New conversation" });
    }
    // TEST MODE: ownership check disabled because the preview iframe resets localStorage
    // between sessions (anonId changes on every reload). Re-enable before production.


    const last = messages[messages.length - 1];
    if (last && last.role === "user") {
      const { error: insErr } = await admin.from("chat_messages").insert({
        thread_id: threadId,
        user_id: anonId,
        role: "user",
        parts: last.parts ?? [],
        message_id: last.id ?? null,
      });
      if (insErr) console.error("[management-agent] insert user msg failed", insErr);

      if (thread?.title === "New conversation" || !thread) {
        const text = (last.parts ?? [])
          .filter((p: { type: string }) => p.type === "text")
          .map((p: { text?: string }) => p.text ?? "")
          .join(" ")
          .slice(0, 80);
        if (text) {
          await admin.from("chat_threads").update({ title: text }).eq("id", threadId);
        }
      }
    }

    const tools = buildTools(mode, bffAuth);
    const errorRule = `\n\nIMPORTANT: When a tool result has \`ok: false\`, DO NOT narrate or interpret the error. Output exactly one short line in the user's language: \`工具呼叫失敗，請見上方錯誤卡。\` and STOP. Do not retry, do not explain authorization or status codes.`;
    const result = streamText({
      model: gateway("google/gemini-3-flash-preview"),
      system: BASE_SYSTEM_PROMPT + modeHint(mode) + errorRule,
      messages: await convertToModelMessages(messages),
      tools,
      stopWhen: stepCountIs(mode === "agent" ? 80 : 50),
    });

    return result.toUIMessageStreamResponse({
      originalMessages: messages,
      headers: responseHeaders,
      onFinish: async ({ responseMessage }) => {
        try {
          await admin.from("chat_messages").insert({
            thread_id: threadId,
            user_id: anonId,
            role: "assistant",
            parts: responseMessage.parts ?? [],
            message_id: responseMessage.id ?? null,
          });
          await admin.from("chat_threads").update({ updated_at: new Date().toISOString() }).eq("id", threadId);
        } catch (e) {
          console.error("[management-agent] persist assistant failed", e);
        }
      },
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error("[management-agent] error", msg);
    const status = msg.includes("429") ? 429 : msg.includes("402") ? 402 : 500;
    return new Response(JSON.stringify({ error: msg }), {
      status, headers: { ...responseHeaders, "Content-Type": "application/json" },
    });
  }
});
