// BFF Contract v1 — public surface.
// VITE_BFF_MODE = "mock" (default) | "live".

export * from "./dto";
export * from "./errors";
export * from "./headers";
export * from "./paths";
export * from "./client";
export * from "./sse/channels";
export * from "./sse/protocol";
export * from "./sse/bridge";
export * from "./sse/liveSse";
export * from "./lists";
export * from "./degradation";
export * from "./useLiveListV1";
export * from "./writes";
export * from "./me";
export * from "./writeGate";
export * from "./personas";
export * from "./liveStatus";
export * from "./liveTransport";
export * from "./capitalPools";
export * from "./strategies";
export * from "./rankingFormulas";
export * from "./rebalances";
export * from "./deployments";
export * from "./evolution";
export * from "./research";
export * from "./artifacts";
export * from "./capabilities";
export * from "./operations";
export * from "./governance";
export * from "./search";
export * from "./evidenceOperations";
export * from "./agora/agoraReads";
export * from "./v5";
export * from "./v5Client";
export * from "./management";
export * from "./managementConsoleReads";
export * from "./shellSummary";
export * from "./agora/types";
export * from "./agora/governance";
export * from "./tradeJournal";
export * from "./agora/interaction";
export * from "./managementDataSources";
export * from "./managementAi";
export * from "./loopTruthTypes";
export * from "./tradeJourneys";
export * from "./commandReceipt";
export * from "./eventTimestamps";
export * from "./domainReads";
export * from "./runtimeEnv";
export * from "./bffV1";
export { runActionSafe, type RunActionSafeOpts } from "./runActionSafe";
export { useLiveList, useRealtimeStatus } from "./useLiveList";
