// Generated by scripts/contract-drift-check.mjs --write.
// Source: Pantheon AG-XR-001 Agora v1 schema/OpenAPI bundle.
// Do not edit by hand; update the Pantheon bundle, then regenerate.

export const AGORA_CONTRACT_SNAPSHOT = {
  "bundleVersion": "1.0",
  "frozenBy": "AG-XR-001",
  "schemaBundleIndex": "services/control-plane/specs/agora/bundle_index.json",
  "openapiRef": "services/control-plane/openapi/agora_v1.openapi.yaml",
  "files": {
    "specs/agora/agora_user_scope.schema.json": "022e147c94cf2b11cde6dc3af49d04ba8a776c50eed857931b12f12aabd02f80",
    "specs/agora/servant_profile.schema.json": "004c5ebddf25622602f175f9ee10bbba714adf7c24050ecc6101c1bb6cffa0b9",
    "specs/agora/strategy_workshop.schema.json": "d8d1662790f35d61fdaff0580ca488011dd90f4b4007d78e9fb77a5065396aec",
    "specs/agora/strategy_completeness.schema.json": "13a8c0e28a6434b93b221a4d33f8022f87ee6ca4df99627728800117474ce2fa",
    "specs/agora/research_plan.schema.json": "55010d81198a4eef6934cde9392e19d79d014bf3f7ef6d31901b37627bd040d4",
    "specs/agora/research_run_summary.schema.json": "669530ad2aed09133e84344aec7768e375c9cc505728b136d76041366184328b",
    "specs/agora/candidate_pool.schema.json": "679077c2f567502883f0b7735332645df30cccd6752a978379c5eeecd058e3b9",
    "specs/agora/dashboard_recipe.schema.json": "5b9c33653eb8c85b001b5f6f6a802e83e58276a25f6c00e0a030a7094c78a8f6",
    "specs/agora/widget_spec.schema.json": "0749275943dc155afa08dbb8736c336d613daf18b99b42f6c10aec15d2eabedb",
    "specs/agora/trading_event.schema.json": "14bd9e788c855c30a1803a767e66a38efc6f7505bfddf59d3095499d113f02f4",
    "specs/agora/trading_intent.schema.json": "588a0508e6b00206be1361e6337b440b7710df0075d6272adb4e85040be4f7ad",
    "specs/agora/shadow_decision.schema.json": "1414c77ddebb5102b81a10fb57db32520c607daba76cb3736f7eb20eb751b0b2",
    "specs/agora/personalization_event.schema.json": "df7991d19943650a61d58a065182fe4bda20f967b4098a36f36b1ab4b33bcb21",
    "specs/agora/capability_manifest.json": "5988cac6d8ca38fc0c51922086c1cc2564b1bb31b2b36ee276e6d363249e9e3e",
    "openapi/agora_v1.openapi.yaml": "4da5ea91923e40c13a9118ee4f784a5d6627e6cb91e4d4712d8fac244912118f"
  }
} as const;

export const AGORA_SCHEMA_FILES = [
  "agora_user_scope.schema.json",
  "servant_profile.schema.json",
  "strategy_workshop.schema.json",
  "strategy_completeness.schema.json",
  "research_plan.schema.json",
  "research_run_summary.schema.json",
  "candidate_pool.schema.json",
  "dashboard_recipe.schema.json",
  "widget_spec.schema.json",
  "trading_event.schema.json",
  "trading_intent.schema.json",
  "shadow_decision.schema.json",
  "personalization_event.schema.json"
] as const;

export const AGORA_CAPABILITIES = [
  {
    "name": "agora.identity.v1",
    "schemas": [
      "agora_user_scope.schema.json",
      "servant_profile.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core"
    ],
    "bffPathPrefixes": [
      "/bff/agora/sessions",
      "/bff/agora/ask"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.session.v1",
    "schemas": [],
    "bffRouteFamilies": [
      "agora-core",
      "agora-extended"
    ],
    "bffPathPrefixes": [
      "/bff/agora/ask/sessions",
      "/bff/agora/sessions",
      "/bff/agora/inbox",
      "/bff/agora/incoming",
      "/bff/agora/messages",
      "/bff/agora/handoffs",
      "/bff/channels"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.workshop.v1",
    "schemas": [
      "strategy_workshop.schema.json",
      "strategy_completeness.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core",
      "agora-extended"
    ],
    "bffPathPrefixes": [
      "/bff/agora/evaluation-runs",
      "/bff/agora/evaluation-suites",
      "/bff/agora/training-examples",
      "/bff/agora/skill-coaching",
      "/bff/agora/committee",
      "/bff/agora/committee-sessions",
      "/bff/agora/persona-lab"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.research.v1",
    "schemas": [
      "research_plan.schema.json",
      "research_run_summary.schema.json",
      "candidate_pool.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core"
    ],
    "bffPathPrefixes": [
      "/bff/agora/research-tasks",
      "/bff/research/tasks"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.trading.v1",
    "schemas": [
      "trading_event.schema.json",
      "trading_intent.schema.json",
      "shadow_decision.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core"
    ],
    "bffPathPrefixes": [
      "/bff/agora/signals",
      "/bff/agora/feedback"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.dashboard.v1",
    "schemas": [
      "dashboard_recipe.schema.json",
      "widget_spec.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core"
    ],
    "bffPathPrefixes": [
      "/bff/agora/daily",
      "/bff/agora/markets",
      "/bff/agora/market-notes",
      "/bff/agora/watchlist",
      "/bff/agora/postmortems",
      "/bff/agora/alerts",
      "/bff/agora/journal",
      "/bff/agora/notes",
      "/bff/agora/decision-journal"
    ],
    "authLevel": "operator"
  },
  {
    "name": "agora.personalization.v1",
    "schemas": [
      "personalization_event.schema.json"
    ],
    "bffRouteFamilies": [
      "agora-core"
    ],
    "bffPathPrefixes": [
      "/bff/agora/memory",
      "/bff/agora/insights",
      "/bff/insights",
      "/bff/memory"
    ],
    "authLevel": "operator"
  }
] as const;

export const AGORA_ROUTE_PATHS = [
  "/bff/agora/sessions",
  "/bff/agora/sessions/{session_id}",
  "/bff/agora/sessions/{session_id}/messages",
  "/bff/agora/ask",
  "/bff/agora/ask/sessions",
  "/bff/agora/ask/sessions/{session_id}",
  "/bff/agora/ask/sessions/{session_id}/close",
  "/bff/agora/messages/{message_id}/actions/{action}",
  "/bff/agora/inbox",
  "/bff/agora/incoming",
  "/bff/agora/handoffs",
  "/bff/channels",
  "/bff/channels/{channel_id}",
  "/bff/agora/evaluation-runs",
  "/bff/agora/evaluation-suites",
  "/bff/agora/training-examples",
  "/bff/agora/skill-coaching/sessions",
  "/bff/agora/committee-sessions",
  "/bff/agora/committee/sessions",
  "/bff/agora/committee/sessions/{committee_session_id}",
  "/bff/agora/committee/sessions/{committee_session_id}/open",
  "/bff/agora/committee/sessions/{committee_session_id}/close",
  "/bff/agora/committee/sessions/{committee_session_id}/memos",
  "/bff/agora/committee/sessions/{committee_session_id}/memos/{memo_id}",
  "/bff/agora/committee/sessions/{committee_session_id}/memos/{memo_id}/publish",
  "/bff/agora/committee/{committee_session_id}/evidence-pack",
  "/bff/agora/committee/{committee_session_id}/evidence-pack/files",
  "/bff/agora/persona-lab/runs",
  "/bff/agora/persona-lab/{run_id}/actions/submit-commit",
  "/bff/agora/research-tasks",
  "/bff/research/tasks",
  "/bff/agora/signals",
  "/bff/agora/signals/{signal_id}",
  "/bff/agora/signals/{signal_id}/feedback",
  "/bff/agora/feedback",
  "/bff/agora/daily",
  "/bff/agora/markets",
  "/bff/agora/market-notes",
  "/bff/agora/watchlist",
  "/bff/agora/postmortems",
  "/bff/agora/alerts/triage",
  "/bff/agora/decision-journal",
  "/bff/agora/journal",
  "/bff/agora/journal/{entry_id}",
  "/bff/agora/notes",
  "/bff/agora/memory",
  "/bff/agora/memory/{memory_id}/actions/{action}",
  "/bff/memory/{memory_id}/actions/quarantine",
  "/bff/agora/insights",
  "/bff/agora/insights/{insight_id}/actions/{action}",
  "/bff/insights/{insight_id}/actions/attach-strategy"
] as const;

export type AgoraContractFile = keyof typeof AGORA_CONTRACT_SNAPSHOT.files;
export type AgoraSchemaFile = (typeof AGORA_SCHEMA_FILES)[number];
export type AgoraCapabilityName = (typeof AGORA_CAPABILITIES)[number]["name"];
export type AgoraRoutePath = (typeof AGORA_ROUTE_PATHS)[number];

export interface AgoraUserScope {
  "spec_version": "1.0";
  "scope_id": string;
  "operator_id": string;
  "granted_capabilities": Array<string>;
  "denied_capabilities"?: Array<string>;
  "surfaces"?: Array<"management" | "agora" | "developer">;
  "persona_ids"?: Array<string>;
  "created_at": string;
  "expires_at"?: string;
  "policy_refs"?: Array<string>;
  "metadata"?: Record<string, unknown>;
}

export interface ServantProfile {
  "spec_version": "1.0";
  "persona_id": string;
  "display_name": string;
  "status": "active" | "suspended" | "paper_only" | "shadow_only" | "retired";
  "capability_summary": {
    "can_ask": boolean;
    "can_research": boolean;
    "can_workshop": boolean;
    "can_shadow"?: boolean;
    "asset_classes"?: Array<string>;
    "strategy_families"?: Array<string>;
  };
  "description"?: string;
  "avatar_ref"?: string;
  "last_active_at"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface StrategyWorkshop {
  "spec_version": "1.0";
  "workshop_id": string;
  "operator_id": string;
  "status": "open" | "in_review" | "concluded" | "archived";
  "subject": {
    "kind": "strategy_spec" | "research_plan" | "candidate_artifact" | "free_form";
    "ref": string;
    "title"?: string;
  };
  "participant_persona_ids"?: Array<string>;
  "completeness_ref"?: string;
  "research_plan_refs"?: Array<string>;
  "message_count"?: number;
  "created_at": string;
  "concluded_at"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface StrategyCompleteness {
  "spec_version": "1.0";
  "completeness_id": string;
  "strategy_ref": string;
  "workshop_id"?: string;
  "assessed_by_persona_id": string;
  "overall_grade": "complete" | "mostly_complete" | "partial" | "incomplete";
  "dimensions": Array<{
    "dimension": "hypothesis" | "data_dependencies" | "market_scope" | "evaluation_plan" | "risk_constraints" | "execution_profile" | "governance";
    "grade": "complete" | "partial" | "missing";
    "gaps"?: Array<string>;
    "required_actions"?: Array<string>;
  }>;
  "blockers"?: Array<string>;
  "research_ready"?: boolean;
  "assessed_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface ResearchPlan {
  "spec_version": "1.0";
  "plan_id": string;
  "strategy_ref": string;
  "workshop_id"?: string;
  "completeness_id"?: string;
  "emitted_by_persona_id": string;
  "status": "draft" | "approved" | "running" | "completed" | "cancelled";
  "objectives": Array<string>;
  "data_requirements": Array<{
    "ref": string;
    "kind": "dataset" | "feature_set" | "market_data" | "alternative_data" | "internal_signal";
    "description"?: string;
  }>;
  "evaluation_criteria": {
    "primary_metric": string;
    "min_sharpe": number;
    "max_drawdown": number;
    "additional_metrics"?: Array<string>;
    "oos_period"?: string;
  };
  "execution_constraints"?: {
    "max_runtime_hours"?: number;
    "compute_tier"?: "light" | "standard" | "heavy";
    "environments"?: Array<"research" | "paper">;
  };
  "run_ids"?: Array<string>;
  "created_at": string;
  "approved_at"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface ResearchRunSummary {
  "spec_version": "1.0";
  "run_id": string;
  "plan_id": string;
  "strategy_ref": string;
  "status": "running" | "completed" | "failed" | "cancelled";
  "outcome": "pass" | "fail" | "inconclusive" | "pending";
  "metrics_summary"?: {
    "sharpe"?: number;
    "max_drawdown"?: number;
    "total_return"?: number;
    "win_rate"?: number;
    "trade_count"?: number;
    [key: string]: unknown;
  };
  "candidate_artifact_ref"?: string;
  "failure_reason"?: string;
  "environment"?: "research" | "paper";
  "started_at"?: string;
  "completed_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface CandidatePool {
  "spec_version": "1.0";
  "pool_id": string;
  "operator_id": string;
  "filter"?: {
    "asset_classes"?: Array<string>;
    "strategy_families"?: Array<string>;
    "lifecycle_states"?: Array<"candidate" | "review" | "approved">;
    "persona_ids"?: Array<string>;
  };
  "candidates": Array<{
    "artifact_id": string;
    "strategy_ref": string;
    "title"?: string;
    "lifecycle_state": "candidate" | "review" | "approved" | "rejected";
    "producing_persona_id"?: string;
    "sharpe_summary"?: number;
    "run_ref"?: string;
    "created_at": string;
  }>;
  "total"?: number;
  "snapshot_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface DashboardRecipe {
  "spec_version": "1.0";
  "recipe_id": string;
  "operator_id": string;
  "name": string;
  "surface": "agora_main" | "agora_research" | "agora_trading" | "agora_workshop";
  "is_default"?: boolean;
  "widgets": Array<{
    "widget_id": string;
    "position": {
      "row": number;
      "col": number;
      "row_span"?: number;
      "col_span"?: number;
    };
    "override_config"?: Record<string, unknown>;
  }>;
  "version"?: number;
  "created_at": string;
  "updated_at"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface WidgetSpec {
  "spec_version": "1.0";
  "widget_id": string;
  "widget_type": "market_summary" | "signal_list" | "candidate_pool" | "research_task_list" | "persona_status" | "watchlist" | "insight_feed" | "alert_triage" | "session_history" | "decision_journal" | "postmortem_feed" | "custom";
  "title"?: string;
  "data_source": {
    "bff_path": string;
    "query_params"?: Record<string, string>;
    "sse_channel"?: string;
    "refresh_interval_seconds"?: number;
  };
  "display_options"?: {
    "max_items"?: number;
    "show_sparkline"?: boolean;
    "compact_mode"?: boolean;
    "theme_variant"?: "default" | "dark" | "compact" | "expanded";
    [key: string]: unknown;
  };
  "persona_filter"?: Array<string>;
  "created_at": string;
  "updated_at"?: string;
  "metadata"?: Record<string, unknown>;
}

export interface TradingEvent {
  "spec_version": "1.0";
  "event_id": string;
  "operator_id": string;
  "persona_id"?: string;
  "session_id"?: string;
  "event_type": "signal_observed" | "price_alert_triggered" | "position_threshold_crossed" | "market_condition_noted" | "news_event_captured" | "trader_decision_noted" | "pattern_flagged";
  "subject"?: {
    "symbol"?: string;
    "asset_class"?: string;
    "venue"?: string;
    "strategy_ref"?: string;
    [key: string]: unknown;
  };
  "event_data"?: Record<string, unknown>;
  "signal_ref"?: string;
  "confidence"?: number;
  "learning_eligible"?: boolean;
  "no_order_route_proof": "agora_observation_only" | "research_plane_only";
  "observed_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface TradingIntent {
  "spec_version": "1.0";
  "intent_id": string;
  "operator_id": string;
  "persona_id"?: string;
  "session_id"?: string;
  "intent_type": "buy_interest" | "sell_interest" | "hold_decision" | "reduce_exposure" | "increase_exposure" | "hedge_intent" | "exit_intent" | "entry_interest";
  "direction": "long" | "short" | "neutral" | "reduce" | "exit";
  "subject": {
    "symbol": string;
    "asset_class"?: string;
    "venue"?: string;
    "strategy_ref"?: string;
  };
  "rationale"?: string;
  "size_hint"?: "small" | "medium" | "large" | "full_position";
  "timeframe_hint"?: string;
  "confidence"?: number;
  "linked_event_ids"?: Array<string>;
  "learning_eligible"?: boolean;
  "no_order_route_proof": "agora_intent_record_only";
  "expressed_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface ShadowDecision {
  "spec_version": "1.0";
  "decision_id": string;
  "shadow_persona_id": string;
  "reference_operator_id": string;
  "reference_intent_id"?: string;
  "session_id"?: string;
  "market_context_ref": string;
  "decision": {
    "action": "buy" | "sell" | "hold" | "reduce" | "hedge" | "exit" | "no_action";
    "subject": {
      "symbol": string;
      "asset_class"?: string;
      "venue"?: string;
    };
    "direction"?: "long" | "short" | "neutral" | "reduce" | "exit";
    "size_hint"?: "small" | "medium" | "large" | "full_position";
    "rationale"?: string;
    "confidence"?: number;
  };
  "agreement_with_human"?: "agree" | "partial_agree" | "disagree" | "not_compared";
  "divergence_rationale"?: string;
  "evaluation_context"?: "paper" | "research";
  "imitation_dataset_eligible"?: boolean;
  "no_order_route_proof": "shadow_learn_only";
  "decided_at": string;
  "metadata"?: Record<string, unknown>;
}

export interface PersonalizationEvent {
  "spec_version": "1.0";
  "event_id": string;
  "operator_id": string;
  "persona_id"?: string;
  "session_id"?: string;
  "event_type": "dashboard_recipe_changed" | "widget_added" | "widget_removed" | "widget_reordered" | "persona_preference_set" | "watchlist_updated" | "alert_threshold_set" | "display_mode_changed" | "memory_endorsed" | "memory_quarantined" | "insight_acted_on" | "notification_preference_set";
  "target"?: {
    "target_type"?: "dashboard_recipe" | "widget" | "persona" | "watchlist" | "alert" | "memory_entry" | "insight" | "notification_rule";
    "target_id"?: string;
  };
  "before_state"?: Record<string, unknown>;
  "after_state"?: Record<string, unknown>;
  "source"?: "operator_action" | "persona_suggestion" | "system_default";
  "memory_writeback_eligible"?: boolean;
  "occurred_at": string;
  "metadata"?: Record<string, unknown>;
}

export type AgoraSchema = AgoraUserScope | ServantProfile | StrategyWorkshop | StrategyCompleteness | ResearchPlan | ResearchRunSummary | CandidatePool | DashboardRecipe | WidgetSpec | TradingEvent | TradingIntent | ShadowDecision | PersonalizationEvent;

export interface AgoraSchemaByTitle {
  AgoraUserScope: AgoraUserScope;
  ServantProfile: ServantProfile;
  StrategyWorkshop: StrategyWorkshop;
  StrategyCompleteness: StrategyCompleteness;
  ResearchPlan: ResearchPlan;
  ResearchRunSummary: ResearchRunSummary;
  CandidatePool: CandidatePool;
  DashboardRecipe: DashboardRecipe;
  WidgetSpec: WidgetSpec;
  TradingEvent: TradingEvent;
  TradingIntent: TradingIntent;
  ShadowDecision: ShadowDecision;
  PersonalizationEvent: PersonalizationEvent;
}
